---
# tasks file for alertmanager
- name: create alertmanager system group
  group:
    name: "{{ group }}"
    system: true
    state: present

- name: create alertmanager system user
  user:
    name: "{{ user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ group }}"
    createhome: false

- name: make alertmanager binary directory
  file:
    path: "{{ binary_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: create configuration directory
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: root
    group: "{{ group }}"
    mode: 0755

- name: create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: get binary
  get_url:
    url: "{{ package_url }}"
    dest: /tmp

- name: extract file
  unarchive:
    src: /tmp/alertmanager-0.22.0-rc.2.linux-amd64.tar.gz
    dest: /tmp
    creates: /tmp/alertmanager
    remote_src: yes

- name: move binary files
  copy:
    src: "/tmp/alertmanager-0.22.0-rc.2.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/alertmanager/{{ item }}"
    remote_src: yes
    mode: 0755
    owner: root
    group: root
  with_items:
    - alertmanager
    - amtool

- name: move configuration file
  copy:
    src: "alertmanager.yml"
    dest: "{{ config_dir }}/alertmanager.yml"
  notify:
    - restart alertmanager

- name : move service file
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644

- name: start service
  systemd:
    daemon_reload: true
    name: alertmanager
    state: started
    enabled: true

