---
# tasks file for monitoring

- name: create prometheus system group
  group:
    name: "{{ group }}"
    system: true
    state: present

- name: create prometheus system user
  user:
    name: "{{ user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ group }}"
    createhome: false

- name: make prometheus binary directory
  file:
    path: "{{ binary_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: create configuration directory
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: root
    group: "{{ group }}"
    mode: 0755

- name: create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: get binary
  get_url:
    url: "{{ package_url }}"
    dest: /tmp

- name: extract file
  unarchive:
    src: /tmp/prometheus-2.27.0.linux-amd64.tar.gz
    dest: /tmp
    creates: /tmp/prometheus
    remote_src: yes

- name: move binary files
  copy:
    src: "/tmp/prometheus-2.27.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/prometheus/{{ item }}"
    remote_src: yes
    mode: 0755
    owner: root
    group: root
  with_items:
    - prometheus
    - promtool

- name: move configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}/{{ item }}"
    mode: 0755
  with_items:
    - prometheus.yml
    - rules.yml
  notify:
    - restart prometheus

- name : move service file
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644

- name: start service
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true