name: lint
on: [push]
jobs:
  lint-role:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.8
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint[core]
      - name: lint role
        run: ansible-lint roles/prometheus
